### ISSUE TITLE
Turn this into separate boards

### ISSUE THREAD

**Issue by spralja** [miningape/pychart#17]

**Comment by spralja** [comment]
I moved the backend project board to spralja/pychart-backend.
I think that we should have the front-end board in the front end repo if that exists.
But it's a bit confusing rn. Maybe it'd be better if we had one webapp repo, with the front end and back end?

@SirPaws

**Comment by SirPaws** [comment]
I haven't made a repo yet, but I'm fine with yeeting it into the backend one

**Comment by spralja** [comment]
Allright, I've changed the name of the repo to https://github.com/spralja/pychart-webapp
